server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 0 # 选择哪个默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.atwangjin.yyb.pojo
  configuration:
      # 自动驼峰命名
      map-underscore-to-camel-case: false
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.atwangjin.yyb.mapper: info

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer
